# redis connection information
redis:
  host: localhost
  port: 6379
  username: ""
  password: ""

# ac_logger configuration
logger:
  level: debug
  full_timestamp: true
  output_file_path: ""

# server information
server:
  app: App-A
  routines:
    - role: producer
      q: req-q #group req-q-consumer-group
      name: producerA
      message:
        format: "{{.App}}-{{.Producer}}-{{.Time}}"
        freq: 1000
    - role: consumer
      q: req-q
      name: consumerX
      processing_time: 500
      refresh_time: 5000