# redis connection information
redis:
  host:
  port: 6379
  username: ""
  password: ""

# act_app_logger configuration
app_logger:
  level: info
  full_timestamp: true
  output_file_path: "./logs/"

# ac library logger configuration
ac_logger:
  level: debug
  output_file_path: ""

# application information
application:
  app: App-A
  routines:
    - role: producer
      q: req-a-q #group req-q-consumer-group
      name: producerA
      message:
        format: "{{.App}}-{{.Producer}}-{{.Time}}"
        freq: 100
    - role: consumer
      q: req-a-q
      name: consumerX
      processing_time: 1000
      refresh_time: 5000
      claim_time: 500
      block_time: 200
    - role: consumer
      q: req-a-q
      name: consumerY
      processing_time: 1000
      refresh_time: 500
      block_time: 200
      msg_idle_time: 500